OASysterm_Ver_Django/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('OAsysterm.urls')),
    path('accounts/',include('django.contrib.auth.urls')),

]

OAsysterm/urls.py
from django.urls import path
from . import views

app_name = 'OAsysterm'

urlpatterns = [
    path('index/', views.IndexView.as_view(), name='index'),
    path('', views.IndexView.as_view(), name='index'),
    path('detail/<int:pk>', views.ProcessDetailView.as_view(), name='detail'),
    path('sign-logout/', views.logout_site, name='logout'),
    path('sys/accounts/', views.AccountManageView.as_view(), name='account_manage'),
    path('sys/add/', views.AddAccountsView.as_view(), name='add_account'),
    path('sys/edit/<int:pk>', views.edit_account, name='edit_account'),
    path('sys/delete/<int:pk>', views.delete_account, name='delete_account'),
    path('startprocess/', views.start_process_view, name='start_process'),
    path('myprocess/', views.MyProcessesView.as_view(), name='my_processes'),
    path('myprocess/detail/<int:pk>', views.MyProcessDetailView.as_view(), name='my_process_detail'),
]

OAsysterm/models.py
from datetime import datetime
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.utils import timezone


# 职位,分别为'Staff','Manager','Boss'
class Position(models.Model):
    position_name = models.CharField(max_length=20)

    @staticmethod
    def insert_positions():
        '''将职位自动添加到数据库中'''
        positions = ['Staff', 'Manager', 'Boss', ]
        for p in positions:
            position = Position.objects.filter(position_name=p).first()
            if position is None:
                Position.objects.create(position_name=p)


class MyUserManager(BaseUserManager):
    def create_user(self, username, password, **extra_fields):#u=models.MyUser(username='wangjie',real_name='WangJie',position='Boss'
        now = timezone.now()
        user = self.model(username=username, last_login=now, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, username, password, **extra_fields):
        u = self.create_user(username, password, **extra_fields)
        u.is_admin = True
        u.save()
        return u


class MyUser(AbstractBaseUser):
    username = models.CharField(max_length=30, unique=True, db_index=True)
    password = models.CharField(max_length=128)
    real_name = models.CharField(max_length=20, default=None)
    position = models.ForeignKey(Position, on_delete=models.CASCADE, null=True)
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['real_name']
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    def get_full_name(self):
        return self.username

    def get_short_name(self):
        return self.username

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

    objects = MyUserManager()


#  流程模型
class Processes(models.Model):
    theme = models.CharField(max_length=256)
    contents = models.TextField()
    #  发起流程的开始时间
    initial_time = models.DateTimeField(default=timezone.now())
    #  审批一次,timestamp改变一次
    timestamp = models.DateTimeField(default=timezone.now())
    # 下一个审批人的名字,'None'表示走到尽头,审批完成
    next_approver = models.CharField(max_length=20, default=None, null=True)
    #  序列号
    process_serial_num = models.CharField(max_length=128, default=datetime.utcnow().strftime('%Y%m%d%H%M%S'))
    # level:High,Normal
    level = models.CharField(max_length=10)
    #  状态，有两种，同意或者不同意
    status = models.CharField(max_length=20, default='agree')
    author = models.ForeignKey(MyUser, on_delete=models.CASCADE)


class ProcessComments(models.Model):
    comments = models.TextField()
    comments_stauts = models.CharField(max_length=20)  # 同意或者不同意
    comments_time = models.DateTimeField(default=timezone.now())
    comments_author = models.CharField(max_length=20)
    process = models.ForeignKey(Processes, on_delete=models.CASCADE)

OAsysterm/forms.py
from django import forms
from django.forms import ValidationError,ModelForm
from django.contrib.auth.hashers import make_password,check_password
from .models import ProcessComments,MyUser,Position,Processes


#  构造审批流程的表单
class ApprovalFrom(forms.Form):
    CHOICES=[('agree', 'Agree'), ('disagree', 'Disagree')]
    comments=forms.CharField(label='Comments:',widget=forms.Textarea(
        attrs={'class':'form-control','placeholder':"Please input your comments"}))
    agreement=forms.ChoiceField(label='Agree?',choices=CHOICES)

    def save(self,author,process):
        cd=self.cleaned_data
        comments=cd['comments']
        agreement=cd['agreement']
        ProcessComments.objects.create(comments=comments,comments_stauts=agreement,
                                       comments_author=author,process=process)

# 构造添加新账户表单
class AddAccountForm(forms.Form):
    #  职位有3个,Staff,Manager,Boss
    CHOICES = [('Staff', 'Staff'), ('Manager', 'Manager'), ('Boss', 'Boss')]
    username=forms.CharField(label='Username:',widget=forms.TextInput(
        attrs={'class':'form-control','placeholder':'Username for login'}))

    realname=forms.CharField(label='Real Name:',widget=forms.TextInput(
        attrs={'class':'form-control'}))
    position=forms.ChoiceField(label='Job position:',choices=CHOICES,widget=forms.Select(attrs={'class':'form-control'}))


    old_password=forms.CharField(label='Old password:',required=False,widget=forms.PasswordInput(
        attrs={'class':'form-control','placeholder': 'If you write nothing,origional password will not be changed.'}),)

    new_password=forms.CharField(label='New password:',required=False,widget=forms.PasswordInput(
        attrs={'class':'form-control',}))

    confirm_password=forms.CharField(label="Confirm new password:",required=False,widget=forms.PasswordInput(
        attrs={'class':'form-control',}))
    is_admin = forms.BooleanField(label='Is Administrator?', required=False)

    #def clean_username(self):
     #   username=self.cleaned_data['username']
      #  if MyUser.objects.filter(username=username).exists():
       #     raise ValidationError("The Account name already exists,please try another one.")
        #return username


    def save(self):
        cd=self.cleaned_data
        username=cd['username']
        realname=cd['realname']
        position=cd['position']
        p=Position.objects.filter(position_name=position).first()
        is_admin=cd['is_admin']
        #  在添加用户的时候，不需要手动设置密码,默认密码是'1111',密码采用哈希值保存
        MyUser.objects.create(username=username,password=make_password('1111'),
                              real_name=realname,position=p,is_admin=is_admin)

    def check_username(self):
        '''检查输入框的用户名，防止重复'''
        username = self.cleaned_data['username']
        if MyUser.objects.filter(username=username).exists():
            return False
        return True
    def check_new_and_old_password(self):
        '''检查输入框的密码情况'''
        if self.cleaned_data['old_password'] != '' and self.cleaned_data['new_password'] != '' and \
                self.cleaned_data['new_password'] == self.cleaned_data['confirm_password']:
            return True
        return False

OAsysterm/views.py
import markdown
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView, ListView, FormView
from django.views.generic.edit import FormMixin
from django.contrib.auth import logout
from django.contrib import messages
from django.utils import timezone
from django.contrib.auth.hashers import make_password
from .models import MyUser, Processes, Position
from .forms import ApprovalFrom, AddAccountForm

PAGINATION_NUM_PER_PAGE = 5


@login_required
def logout_site(request):
    logout(request)
    return HttpResponseRedirect('/accounts/login/')


class IndexView(LoginRequiredMixin, ListView):
    """此视图为用户登录后进入系统的首页，显示该用户需要审批的流程"""
    login_url = '/accounts/login/'
    redirect_field_name = 'redirect_to'
    model = Processes
    template_name = 'main/index.html'
    context_object_name = 'process'
    paginate_by = PAGINATION_NUM_PER_PAGE

    def get_queryset(self):
        current_user = self.request.user
        return super().get_queryset().filter(next_approver=current_user.username)


# 详情页面，并进行流程审批
class ProcessDetailView(LoginRequiredMixin, FormMixin, DetailView):
    login_url = '/accounts/login/'
    redirect_field_name = 'redirect_to'

    model = Processes
    template_name = 'main/detail.html'
    context_object_name = 'process'
    form_class = ApprovalFrom
    success_url = reverse_lazy('OAsysterm:index')

    def get_context_data(self, **kwargs):
        form = ApprovalFrom()
        context = super().get_context_data()
        next_users = None
        #  如果当前用户的职位是Boss，则流程没有下一位审批人,流程结束;
        #   否则下一位审批人是比当前用户职位高一个等级的用户.
        # 职位有三个,从低到到依次为staff, manager,boss, id分别为1,2,3
        if self.request.user.position.position_name != 'Boss':
            next_users = MyUser.objects.filter(
                position=Position.objects.get(pk=self.request.user.position.id + 1)).all()
        context.update({'form': form, 'next_users': next_users})
        return context

    def get_object(self, queryset=None):
        self.process = super().get_object(queryset=None)
        return super().get_object(queryset=None)

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        self.process.next_approver = self.request.POST.get('nextuser')
        self.process.timestamp = timezone.now()
        self.process.save()
        form.save(author=self.request.user, process=self.process)
        return super().form_valid(form)


class AccountManageView(LoginRequiredMixin, ListView):
    """管理帐号,显示账号基本概况.有两种情况,如果当前用户是管理员权限,
    则显示系统所有的用户信息;否则只显示当前用户信息"""
    login_url = '/accounts/login/'
    redirect_field_name = 'redirect_to'

    model = MyUser
    template_name = 'main/account_manage.html'
    context_object_name = 'users'
    paginate_by = PAGINATION_NUM_PER_PAGE

    def get_queryset(self):
        current_user = self.request.user
        if current_user.is_admin:
            return super().get_queryset().order_by('pk')
        else:
            return super().get_queryset().filter(username=current_user.username)


#  增加新账号，仅管理员可用
class AddAccountsView(LoginRequiredMixin, FormView):
    login_url = '/accounts/login/'
    redirect_field_name = 'redirect_to'
    template_name = 'main/add_account.html'
    form_class = AddAccountForm
    success_url = reverse_lazy('OAsysterm:account_manage')

    def form_valid(self, form):
        if form.check_username():
            form.save()
        else:
            messages.add_message(self.request, messages.INFO, "The username already exists,please try another one.")
        return super().form_valid(form)


#  删除账号，仅管理员可用
@login_required
def delete_account(request, pk):
    if request.user.is_admin:
        u = MyUser.objects.get(pk=pk)
        u.delete()
    else:
        messages.add_message(request, messages.INFO, "You can't delete it.")
    return HttpResponseRedirect(reverse('OAsysterm:account_manage'))


@login_required
def edit_account(request, pk):
    """编辑账户信息.有三种情况:
        1,当前用户是管理员且编辑对象是当前用户，则可以编辑账号名、密码、真实姓名、职位、权限;
        2,当前用户是管理员但编辑其他用户信息，则不可以改密码:,可以编辑账号名、真实姓名、职位、权限;
        3,当前用户不是管理员，则只能修改本人密码、真实姓名"""
    edit_user = get_object_or_404(MyUser, pk=pk)
    current_user = request.user
    if request.method == 'POST':
        form = AddAccountForm(request.POST)
        if form.is_valid():
            p = Position.objects.filter(position_name=form.cleaned_data['position']).first()
            is_admin = form.cleaned_data['is_admin']
            edit_user.real_name = form.cleaned_data['realname']
            if current_user == edit_user:
                #  首先检查密码的输入情况.如果没有输入密码或新密码与再一次确认的密码不一致,则密码不改动;
                # 如果输入密码,则验证密码是否正确,随后改动密码
                if form.check_new_and_old_password():
                    # user类内置的验证密码函数:check_password
                    if edit_user.check_password(form.cleaned_data['old_password']):
                        edit_user.password = make_password(form.cleaned_data['new_password'])
                        messages.add_message(request, messages.INFO, 'Password has been changed!')
                    else:
                        messages.add_message(request, messages.INFO, 'The old password is incorrect!')
                else:
                    messages.add_message(request, messages.INFO, 'Password has not been changed!')
                #  仅管理员可修改账号名
                if current_user.is_admin:
                    edit_user.username = form.cleaned_data['username']
                    edit_user.is_admin = is_admin
                    edit_user.position = p
                edit_user.save()
                return HttpResponseRedirect(reverse('OAsysterm:account_manage'))
            else:
                if current_user.is_admin:
                    #  只有用户名和原来的用户名不一样且不与其他用户名重复，才储存到数据库
                    if form.cleaned_data['username'] != edit_user.username and form.check_username():
                        edit_user.username = form.cleaned_data['username']
                    elif form.cleaned_data['username'] != edit_user.username:
                        messages.add_message(request, messages.INFO,
                                             "The username already exists,please try another one.")
                    edit_user.is_admin = is_admin
                    edit_user.position = p
                    edit_user.save()
                    return HttpResponseRedirect(reverse('OAsysterm:account_manage'))
    #  初始化表单，让表单填充原先的数据
    form = AddAccountForm(initial={
        'username': edit_user.username,
        'realname': edit_user.real_name,
        'position': edit_user.position.position_name,
        'is_admin': edit_user.is_admin,
    })
    return render(request, template_name='main/edit_account.html', context={'edit_user': edit_user, 'form': form})


@login_required
def start_process_view(request):
    """发起流程.有两种情况,一种是当前用户职位是Boss，则无需发流程;
    其他情况发流程则需要选中下一个比自己职级高一级的人员"""
    next_users = None
    current_user_position_id = request.user.position_id
    # 判断当前用户职位是否比Boss低，id=3就是BOSS职位
    if current_user_position_id < 3:
        next_users = MyUser.objects.filter(position_id=current_user_position_id + 1).all()
    if next_users is None:
        messages.add_message(request, messages.INFO, "You need not create process!")
        return HttpResponseRedirect(reverse('OAsysterm:index'))
    else:
        #  获取表单数据
        if request.method == 'POST':
            #   渲染Markdown文本
            contets_md = markdown.markdown(request.POST.get('contents'))

            Processes.objects.create(
                theme=request.POST.get('theme'),
                contents=contets_md,
                next_approver=request.POST.get('nextuser'),
                level=request.POST.get('level'),
                author=request.user
            )
            return HttpResponseRedirect(reverse('OAsysterm:index'))
    return render(request, template_name='main/startprocess.html', context={'next_users': next_users})


#  显示当前用户已经发起的流程概况
class MyProcessesView(LoginRequiredMixin, ListView):
    login_url = '/accounts/login/'
    redirect_field_name = 'redirect_to'

    model = Processes
    template_name = 'main/myprocess.html'
    context_object_name = 'myprocess'
    paginate_by = PAGINATION_NUM_PER_PAGE

    def get_queryset(self):
        return super().get_queryset().filter(author=self.request.user)


#  进入已发起的流程详情页面
class MyProcessDetailView(LoginRequiredMixin, DetailView):
    login_url = '/accounts/login/'
    redirect_field_name = 'redirect_to'

    model = Processes
    template_name = 'main/myprocess_detail.html'
    context_object_name = 'myprocess'

OAsysterm/templates/main/_edit_form1.html
{{ form.username.label_tag }}
{{ form.username }}
{{ form.realname.label_tag }}
{{ form.realname }}
{{ form.position.label_tag }}
{{ form.position }}
{{ form.is_admin.label_tag }}
{{ form.is_admin }}

OAsysterm/templates/main/_edit_form2.html
{{ form.realname.label_tag }}
{{ form.realname }}
{{ form.old_password.label_tag }}
{{ form.old_password }}
{{ form.new_password.label_tag }}
{{ form.new_password }}
{{ form.confirm_password.label_tag }}
{{ form.confirm_password }}

OAsysterm/templates/main/account_manage.html
{% extends "main/base.html" %}
{% load static %}
{% block head %}
    <title>Manage account</title>
    <link rel="stylesheet" href="{% static 'css/main/account_manage.css' %}">
    <script type="text/javascript">
        <!--在删除账户之前需要确认-->
        function delete_account(url) {
            var mymessage = confirm("Are you sure to delete the account?")
            var host = location.host;
            if (mymessage == true) {
                window.location.href = 'http://' + host + url;
            }
        }

    </script>
{% endblock %}
{% block content %}

    <div class="navbar manage-account">
        <p>Manage account</p>
        {% if user.is_admin %}
            <a href="{% url 'OAsysterm:add_account' %}">
                <button class="btn btn-default add-btn">
                    <span class="glyphicon glyphicon-plus"></span> Add
                </button>
            </a>
        {% endif %}
    </div>
    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th>User ID</th>
            <th>User Name(Account)</th>
            <th>Real Name</th>
            <th>Job Position</th>
            <th>Permission</th>
            <th id="edit"></th>
        </tr>
        </thead>

        {% for u in users %}
            <tbody>
            <tr>
                <td>{{ u.id }}</td>
                <td>{{ u.username }}</td>
                <td>{{ u.real_name }}</td>
                <td>{{ u.position.position_name }}</td>
                <td>{% if u.is_admin %}Administrator{% else %}User{% endif %}</td>
                <td>
                    <a href="{% url 'OAsysterm:edit_account' u.pk %}">
                        <button class="btn btn-warning edit-btn">
                            <span class="glyphicon glyphicon-edit"></span> Edit
                        </button>
                    </a>
                    {% if user.is_admin %}
                        <button class="btn btn-danger delete-btn" onclick="delete_account('/sys/delete/{{ u.pk }}')">
                            <span class="glyphicon glyphicon-trash"></span> Delete
                        </button>
                        </a>
                    {% endif %}
                </td>
            </tr>
            </tbody>
        {% endfor %}

    </table>
    <!--实现分页-->
    {% include "main/_pagiantion.html" %}

{% endblock %}

OAsysterm/templates/main/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
   <!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
      integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<link rel="stylesheet" type="text/css" href="{% static 'css/main/base.css' %}">
<link rel="shortcut icon" href="../../static/img/logo1.png" />
    {% block head %}
    {% endblock %}
</head>
<body>
{% for message in messages %}
<div class="alert alert-warning">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    {{ message }}
</div>
{% endfor %}
<div class="header col-md-12 container-fluid">
    <div class="row">
        <div class="logo col-md-1">
            <img src="../../static/img/logo1.png " height="100%">
        </div>
        <div class="company-name col-md-4">
            <h2>WangJie Company</h2>
            <p>OA information management system</p>
        </div>
        <div class="col-md-7">
            <ul class="list-unstyled list-inline user-list">
                <li>User:<span class="username">{{ user.real_name }}</span></li>
                <li>Position:<span class="position-name">{{ user.position.position_name }}</span></li>
                <li style="border-right: none"><a href="{% url 'OAsysterm:logout' %}">Logout</a></li>
            </ul>
        </div>
    </div>

</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-1 aside">
            <div class="container-fluid">
                <div class="row aside-button">
                    <a href="{% url 'OAsysterm:index' %}">
                        <div class="col-md-12 aside-button ">
                            <span class="glyphicon glyphicon-pencil"></span>Approval Process
                        </div>
                    </a>

                    <a href="{% url 'OAsysterm:start_process' %}">
                        <div class="col-md-12 aside-button ">
                            <span class="glyphicon glyphicon-plus-sign"></span>Start a Process
                        </div>
                    </a>
                    <a href="{% url 'OAsysterm:my_processes' %}">
                        <div class="col-md-12  ">
                            <span class="glyphicon glyphicon-asterisk"></span>My Process
                        </div>
                    </a>
                    <a href="{% url 'OAsysterm:account_manage' %}">
                        <div class="col-md-12 aside-button ">
                            <span class="glyphicon glyphicon-folder-open"></span> Systerm Manage
                        </div>
                    </a>
                </div>
            </div>
        </div>
<div class="col-md-11 content">
        {% block content %}

        {% endblock %}
</div>
    </div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

</body>
</html>

OAsysterm/templates/main/index.html
{% extends "main/base.html" %}

{% load static %}

{% block head %}
    <title>Index</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/main/index.css' %}">
{% endblock %}
{% block content %}
    <div class="navbar">
        <p>Pending process</p>
    </div>
    <div>
        {% if not process %}
            <h2>There is no pending process</h2>
        {% else %}
            <table class="table table-striped table-hover">
                <thead>
                <tr>
                    <th scope="col" id="NO">NO.</th>
                    <th scope="col" id="ProcessID">Serial Num</th>
                    <th scope="col">Theme</th>
                    <th scope="col" id="Initiator">Initiator</th>
                    <th scope="col" id="InitiatalTime">Initiatal Time</th>
                    <th scope="col" id="ArrivedTime">Arrived Time</th>
                    <th scope="col" id="approval-info-sign"></th>
                </tr>
                </thead>
                <tbody>

                {% for p in process %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ p.process_serial_num }}{{ p.id }}</td>
                        <td>{{ p.theme }}</td>
                        <td>{{ p.author.real_name }}</td>
                        <td>{{ p.initial_time|date:"d M Y,H:i:s" }}</td>
                        <td>{{ p.timestamp|date:"d M Y,H:i:s" }}</td>
                        <td><a href="{% url "OAsysterm:detail" pk=p.id %}"><span
                                class="glyphicon glyphicon-info-sign"></span> Detail</a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% endif %}
    </div>

    <!--实现分页-->
    {% include "main/_pagiantion.html" %}

{% endblock %}

OAsysterm/templates/main/myprocess.html
{% extends "main/base.html" %}
{% load static %}
{% block head %}
    <title>MyProcess</title>
<link rel="stylesheet" href="{% static 'css/main/my_process.css' %}">
{% endblock %}
{% block content %}

    <div class="navbar">
        <p>My process</p>
    </div>
    {% if not myprocess %}
    <h2>You don't have any process</h2>
    {% else %}
    <table class="table myprocess  table-hover">
        <thead>
        <tr>
            <th scope="col" id="NO">NO.</th>
            <th scope="col" id="ProcessID">Serial Num</th>
            <th scope="col">Theme</th>
            <th>Level</th>
            <th scope="col" id="InitiatalTime">Initiatal Time</th>
            <th scope="col" id="ArrivedTime">Approval Time</th>
            <th>Status</th>
        </tr>
        </thead>
        <tbody>
        {% for p in myprocess %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ p.process_serial_num }}{{ p.id }}</td>
            <td>{{ p.theme }}</td>
            <td>{{ p.level  }}</td>
            <td>{{ p.initial_time|date:"d M Y,H:i:s" }}</td>
            <td>{{ p.timestamp|date:"d M Y,H:i:s" }}</td>
        <!-- 流程有三种状态,通过,未通过,正在审批-->
            {% if p.next_approver  is None and p.status == 'agree' %}
            <td><a href="{% url 'OAsysterm:my_process_detail' pk=p.pk %}"><button class="btn btn-success myprocess-btn">Passed</button></a></td>
            {% elif p.next_approver is None and p.status == 'disagree' %}
            <td><a href="{% url 'OAsysterm:my_process_detail' pk=p.pk %}"><button class="btn btn-danger myprocess-btn">Didn't pass</button></a></td>
            {% else %}
            <td><a href="{% url 'OAsysterm:my_process_detail' pk=p.pk %}"><button class="btn btn-warning myprocess-btn">Inspecting</button></a></td>
            {% endif %}
        </tr>
        {% endfor %}
        </tbody>
    </table>
    {% endif %}
    <!--实现分页-->
    {% include "main/_pagiantion.html" %}
{% endblock %}

OAsysterm/templates/main/myprocess_detail.html
{% extends "main/base.html" %}
{% load static %}
{% block head %}
    <title>My processes detail</title>
    <link rel="stylesheet" href="{% static 'css/main/my_process_detail.css' %}">
{% endblock %}
{% block content %}
    <div class="navbar">
        <p>Detail</p>
    </div>
    <table class="table table-bordered myprocess-detail-table">
        <tbody>
        <tr>
            <th>Theme</th>
            <td>{{ myprocess.theme }}</td>
            <th>Level</th>
            <td>{{ myprocess.level }}</td>
            <th>Initial time</th>
            <td>{{ myprocess.initial_time|date:"d M Y,H:i:s" }}</td>
            <th>Status</th>
            {% if myprocess.next_approver is None and myprocess.status == 'agree' %}
                <td class="success">Passed</td>
            {% elif myprocess.next_approver is None and myprocess.status == 'disagree' %}
                <td class="danger">Didn't pass</td>
            {% else %}
                <td class="warning">Inspecting</td>
            {% endif %}
        </tr>
        <tr>
            <th id="myprocess-detail-contents-header">Contents</th>
            <td colspan="7" id="myprocess-detail-contents">{{ myprocess.contents|safe }}</td>
        </tr>
        </tbody>
    </table>
    <hr class="hr1">
    {% if myprocess.processcomments_set.all %}
        {% for pc in myprocess.processcomments_set.all %}
            <table class="table table-bordered myprocess-detail-comments-table">
                <tbody>
                <tr>
                    <th id="Comment-by">Comment by <span>{{ pc.comments_author }}</span></th>
                    <td colspan="3"
                        style="text-align: left;vertical-align: top;word-spacing: 4px">{{ pc.comments }}</td>
                </tr>
                <tr>
                    <th>Opinion</th>
                    <td class="comments-opinion">{{ pc.comments_stauts }}</td>
                    <th>Time</th>
                    <td>{{ pc.comments_time|date:"d M Y,H:i:s" }}</td>
                </tr>
                </tbody>
            </table>
        {% endfor %}
    {% endif %}
    {% if myprocess.next_approver %}
        <table class="table-next-approver">
            <tr>
                <th>Next approver:</th>
                <td><i>{{ myprocess.next_approver }}</i></td>
            </tr>
        </table>
    {% endif %}

{% endblock %}